name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v3

      # 2. Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # 3. Install GoReleaser
      - name: Install GoReleaser
        run: |
          curl -sL https://git.io/goreleaser | bash

      # 4. Run GoReleaser
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --rm-dist
